### ISSUE TITLE
Add django-import-export to easily share/migrate configuration options

### ISSUE THREAD

**Issue by sergei-maertens** [GemeenteUtrecht/formulieren-ui#9]
Add import-export functionality for:

* `zgw_consumers.Service`
* `nlx_url_rewrites.URLRewrite`
* `django_camunda.CamundaConfig`
* `config.FormsConfig`

**Comment by sergei-maertens** [comment]
the django-solo based ones might be tricky because there's no list-view, if it's too much effort, you can leave them out

**Comment by annashamray** [comment]
> the django-solo based ones might be tricky because there's no list-view, if it's too much effort, you can leave them out

Yeah, but changing admin template seems to help
